[training_utils] fix: no allocator set when using TMA for kernels
Refer to https://github.com/triton-lang/triton/commit/43625fc968b693ab51884ca95adbcf3e43483fd0

Triton 3.5.0 stores allocators in ContextVar; values do not propagate to new
threads by default. Some execution paths in verl use thread pools (e.g.,
concurrent.futures), so we set the allocator as ContextVar *default* to avoid
falling back to NullAllocator in worker threads.

Related traceback:
```log
   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 456, in result
     return self.__get_result()
            ^^^^^^^^^^^^^^^^^^^
   File "/usr/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
     raise self._exception
            ^^^^^^^^^^^^^^^^^^^^^
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/single_controller/ray/base.py", line 841, in func
     return getattr(self.worker_dict[key], name)(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/single_controller/base/decorator.py", line 456, in inner
     return func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/transferqueue_utils.py", line 314, in dummy_inner
     output = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/profiler/performance.py", line 105, in f
     return self.log(decorated_function, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/profiler/performance.py", line 118, in log
     output = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/profiler/profile.py", line 256, in wrapper
     return func(self_instance, *args, **kwargs_inner)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/workers/megatron_workers.py", line 827, in compute_ref_log_prob
     return self.compute_log_prob(data)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/single_controller/base/decorator.py", line 456, in inner
     return func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/transferqueue_utils.py", line 314, in dummy_inner
     output = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/profiler/performance.py", line 105, in f
     return self.log(decorated_function, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/profiler/performance.py", line 118, in log
     output = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/profiler/profile.py", line 256, in wrapper
     return func(self_instance, *args, **kwargs_inner)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/workers/megatron_workers.py", line 870, in compute_log_prob
     output, entropys, layers_topk_idx = self.actor.compute_log_prob(data=data, calculate_entropy=not is_lora)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/profiler/performance.py", line 105, in f
     return self.log(decorated_function, *args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/profiler/performance.py", line 118, in log
     output = func(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/workers/actor/megatron_actor.py", line 235, in compute_log_prob
     output = self.forward_backward_batch(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/workers/actor/megatron_actor.py", line 693, in forward_backward_batch
     losses_reduced = forward_backward_func(
                      ^^^^^^^^^^^^^^^^^^^^^^
   File "/root/Megatron-Bridge/3rdparty/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 632, in forward_backward_no_pipelining
     output_tensor, num_tokens = forward_step(
                                 ^^^^^^^^^^^^^
   File "/root/Megatron-Bridge/3rdparty/Megatron-LM/megatron/core/pipeline_parallel/schedules.py", line 417, in forward_step
     output_tensor, loss_func = forward_step_func(data_iterator, model)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/workers/actor/megatron_actor.py", line 608, in forward_step
     output = forward_fn(
              ^^^^^^^^^^^
   File "/root/verl/verl/models/mcore/model_forward_fused.py", line 117, in fused_forward_model
     output_orig: CausalLMOutputForPPO = model(**input_args)
                                         ^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
     return forward_call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/Megatron-Bridge/3rdparty/Megatron-LM/megatron/core/distributed/data_parallel_base.py", line 22, in forward
     return self.module(*inputs, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
     return forward_call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/Megatron-Bridge/3rdparty/Megatron-LM/megatron/core/transformer/module.py", line 456, in forward
     outputs = self.module(*inputs, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
     return self._call_impl(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/torch/nn/modules/module.py", line 1786, in _call_impl
     return forward_call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/models/mcore/model_forward_fused.py", line 209, in _fused_GPTModel_forward
     logprobs, entropy = linear_cross_entropy(
                         ^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/torch/autograd/function.py", line 581, in apply
     return super().apply(*args, **kwargs)  # type: ignore[misc]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/kernel/linear_cross_entropy.py", line 77, in forward
     logprobs, entropy, _maximum, _accumulate, _entropy_b = kernels.efficient_entropy_forward(
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/root/verl/verl/utils/kernel/kernels.py", line 626, in efficient_entropy_forward
     efficient_entropy_kernel_general_mainloop[mainloop_grid](
   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 419, in <lambda>
     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/autotuner.py", line 250, in run
     ret = self.fn.run(
           ^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/jit.py", line 757, in run
     kernel.run(grid_0, grid_1, grid_2, stream, kernel.function, kernel.packed_metadata, launch_metadata,
   File "/usr/local/lib/python3.12/dist-packages/triton/backends/nvidia/driver.py", line 709, in __call__
     global_scratch = allocate_scratch(self.global_scratch_size, self.global_scratch_align, _allocation._allocator)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/triton/backends/nvidia/driver.py", line 706, in allocate_scratch
     return alloc_fn(alloc_size, align, stream)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/_allocation.py", line 20, in __call__
     raise RuntimeError("Kernel requires a runtime memory allocation, but no allocator was set. " +
 RuntimeError: Kernel requires a runtime memory allocation, but no allocator was set. Use triton.set_allocator to specify an allocator.
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>