[ci] chore: add documentation coverage test (#2004)
### Checklist Before Starting

- [x] Searched for similar PR(s).
- [x] Checked PR Title format
  - [ ] In format of: [modules] type: Title
- [ ] modules are in `fsdp, megatron, sglang, vllm, rollout, trainer,
tests, training_utils, recipe, hardware, deployment, ray, worker,
single_controller, misc, perf, model, algo, env, tool, ckpt, doc`
  - [ ] type is in `feat, fix, refactor, chore`
- [ ] can involve multiple modules, seperated by `,` or space, like
`[megatron, fsdp, doc] feat: xxx`

### What does this PR do?

Added a test that asserts every function and class imported by a target
file verl/trainer/ppo/ray_trainer.py. We may extend this test further
for all frequently inspected/extended modules.

Example error msg:
```
Docstring verification failed:

 • /opt/tiger/open_verl/verl/trainer/ppo/ray_trainer.py:58 - function `verl.utils.seqlen_balancing.log_seqlen_unbalance` is missing a docstring.
Traceback (most recent call last):
  File "/opt/tiger/open_verl/tests/special_sanity/validate_imported_docs.py", line 136, in <module>
    main()
  File "/opt/tiger/open_verl/tests/special_sanity/validate_imported_docs.py", line 129, in main
    raise Exception("❌ Docstring verification failed.")
Exception: ❌ Docstring verification failed.
```

### Checklist Before Submitting

- [x] Read the [Contribute
Guide](https://github.com/volcengine/verl?tab=readme-ov-file#contribution-guide).
- [x] Apply [pre-commit
checks](https://github.com/volcengine/verl?tab=readme-ov-file#code-linting-and-formatting).
- [ ] Add `[BREAKING]` to the PR title `description` if it breaks any
API.
- [ ] Update the documentation about your changes in the
[docs](https://github.com/volcengine/verl/tree/main/docs).
- [x] New CI unit test(s) are added to cover the code path.
- [ ] Rely on existing unit tests on CI that covers the code path.