Add DeepSeek 671B GRPO example (#1771)
### Checklist Before Starting

- [x] Search for similar PR(s).

### What does this PR do?

Add an example for DeepSeek 671B GRPO

### Specific Changes

- Need https://github.com/volcengine/verl/pull/1694
- Set `torch._dynamo.config.suppress_errors = True` at entrypoint, if 

```
ray.exceptions.RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/ray/exceptions.py", line 46, in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
TypeError: BackendCompilerFailed.__init__() missing 1 required positional argument: 'inner_exception'
```

### Additional Info.

- vllm as backend, sglang working in process
(https://github.com/sgl-project/sglang/issues/6762). Merged when both
backends are ready.
- For DeepSeek-V3-0324 at `gsm8k`, the reward starts from 0.8 and
saturated at around 0.95 using only 3 steps.
- Memory peaks around 90GB during actor update (1.5k input + 2.5k
output), consider using TP/ETP for a lower requirement.
- For gsm8k training using this yaml,


![image](https://github.com/user-attachments/assets/d16cf959-5845-4dd0-95af-07fc35820f18)


### Checklist Before Submitting

- [ ] Read the [Contribute
Guide](https://github.com/volcengine/verl?tab=readme-ov-file#contribution-guide).
- [ ] Apply [pre-commit
checks](https://github.com/volcengine/verl?tab=readme-ov-file#code-linting-and-formatting).
- [ ] Add `[BREAKING]` to the PR title if it breaks any API.
- [ ] Update the documentation about your changes in the
[docs](https://github.com/volcengine/verl/tree/main/docs).
- [ ] Add CI test(s) if necessary.