[installation] doc: Fix pip install instructions (#1353)
### Checklist Before Starting

- [X] Search for similar PR(s).

### What does this PR do?

There should be no space between `.` and `[vllm]` or `[sglang]`, or it
will result in error:

```logs
ERROR: Invalid requirement: '[vllm]': Expected package name at the start of dependency specifier
    [vllm]
```

In addition, I rewrite this part to make the instructions more clear (as
`.. or ..` can't be executed by bash directly)

### Additional Info.

- **Issue Number**: none
- **Training**: none
- **Inference**: none

### Checklist Before Submitting

- [X] Read the [Contribute
Guide](https://github.com/volcengine/verl?tab=readme-ov-file#contribution-guide).
- [X] Apply [pre-commit
checks](https://github.com/volcengine/verl?tab=readme-ov-file#code-linting-and-formatting).
- [X] Add `[BREAKING]` to the PR title if it breaks any API.
- [X] Update the documentation about your changes in the
[docs](https://github.com/volcengine/verl/tree/main/docs).
- [X] Add CI test(s) if neccessary.

Signed-off-by: Hollow Man <hollowman@opensuse.org>