[data] fix: Pass video metadata to vLLM and support change image_patch_size (#3928)
### What does this PR do?
Slove issue in vLLM https://github.com/vllm-project/vllm/issues/27587
1. Support RL training with video when use vLLM as rollout 
<img width="1082" height="592" alt="image"
src="https://github.com/user-attachments/assets/f699ffdb-8cf0-4901-93ec-1623271bd433"
/>

```python
(TaskRunner pid=210367) video_mm_kwargs["do_sample_frames"] = metadata.get(
(TaskRunner pid=210367) ^^^^^^^^^^^^
(TaskRunner pid=210367) AttributeError: 'NoneType' object has no attribute 'get'
```

When use vLLM to generata a request with video, raise an error. Because
verl doesn't pass the metedata to vLLM.

2. Support change `image_patch_size`

`Qwen2.5-VL` use `image_patch_size` 14, but `Qwen3-VL` use
`image_patch_size` 16.
Original code fix this valuet to 14.

### API and Usage Example

```bash
# Add a new args to set image patch size
...
data.video_key=videos \
data.image_patch_size=16 \
actor_rollout_ref.model.path=$MODEL_PATH \
...
```

### Design & Code Changes
1. Add a new argument to change `image_patch_size`. Currently, this
value is fixed to 14. But Qwen3-VL use 16 as `image_patch_size`.
2. When use vLLM to inference a video, need to pass video metadata.
Change the `video` input to vLLM from only videos to videos and video
matadatas tuple.

### Checklist Before Submitting

> [!IMPORTANT]
> Please check all the following items before requesting a review,
otherwise the reviewer might deprioritize this PR for review.

- [ ] Read the [Contribute
Guide](https://github.com/volcengine/verl/blob/main/CONTRIBUTING.md).
- [ ] Apply [pre-commit
checks](https://github.com/volcengine/verl/blob/main/CONTRIBUTING.md#code-linting-and-formatting):
`pre-commit install && pre-commit run --all-files --show-diff-on-failure
--color=always`
- [ ] Add / Update [the
documentation](https://github.com/volcengine/verl/tree/main/docs).
- [ ] Add unit or end-to-end test(s) to [the CI
workflow](https://github.com/volcengine/verl/tree/main/.github/workflows)
to cover all the code. If not feasible, explain why: ...
- [ ] Once your PR is ready for CI, send a message in [the `ci-request`
channel](https://verl-project.slack.com/archives/C091TCESWB1) in [the
`verl` Slack
workspace](https://join.slack.com/t/verl-project/shared_invite/zt-3855yhg8g-CTkqXu~hKojPCmo7k_yXTQ).
(If not accessible, please try [the Feishu group
(飞书群)](https://applink.larkoffice.com/client/chat/chatter/add_by_link?link_token=772jd4f1-cd91-441e-a820-498c6614126a).)

---------

Co-authored-by: gemini-code-assist[bot] <176961590+gemini-code-assist[bot]@users.noreply.github.com>