[training_utils] fix: stop using `math` naming under reward score"
Rename `math.py` files to `math_reward.py` as it's not a good idea
to name a python file that is the same as a system package, as that
can cause conflict. e.g.:

```bash
$ python verl/utils/reward_score/abc.py
Traceback (most recent call last):
  File "/verl/utils/reward_score/abc.py", line 20, in <module>
    import numpy as np
  File "numpy/__init__.py", line 157, in <module>
    from . import random
  File "numpy/random/__init__.py", line 180, in <module>
    from . import _pickle
  File "numpy/random/_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "numpy/random/mtrand.pyx", line 1, in init numpy.random.mtrand
  File "bit_generator.pyx", line 40, in init numpy.random.bit_generator
  File "secrets.py", line 19, in <module>
    from random import SystemRandom
  File "random.py", line 49, in <module>
    from math import log as _log, exp as _exp, pi as _pi, e as _e, ceil as _ceil
ImportError: cannot import name 'log' from 'math' (verl/utils/reward_score/math.py)
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>