Fix ImportError in is_megatron_core_available() and is_vllm_available() Functions (#1131)
Issue: In a Python 3.10 environment, when using import importlib,
calling importlib.util.find_spec('megatron.core') results in the
following error:

https://github.com/volcengine/verl/blob/833e7d78782bcf0dcd92947b90eed142a9e34875/verl/utils/import_utils.py#L21-L30
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'util'
```
This error causes more_spec to be None, which can lead to further issues
in the code execution.

Proposed Solution: I recommend adding import importlib.util to ensure
that the util module is properly imported and available for use. This
change will prevent the AttributeError and allow the find_spec function
to work as intended.

Please see the attached screenshot for reference.
<img width="534" alt="Clipboard_Screenshot_1744872935"
src="https://github.com/user-attachments/assets/92f63ed5-7a52-43ac-86be-2c9585320234"
/>