[misc] feat: init random model supports custom code in the model
We should set `trust_remote_code` to True and init model with
`AutoModelForCausalLM.from_pretrained` instead, so that the models
that require custom code to work can still be modified without any error.

e.g. for Kimi K2, without this change, we will get the following error
as Kimi has some custom model handling code in their repo:

```logs
Traceback (most recent call last):
  File "verl/scripts/init_random_model.py", line 93, in <module>
    init_random_model(
  File "verl/scripts/init_random_model.py", line 83, in init_random_model
    model = AutoModelForCausalLM.from_config(new_confg)
  File "transformers/models/auto/auto_factory.py", line 456, in from_config
    return model_class._from_config(config, **kwargs)
  File "transformers/modeling_utils.py", line 277, in _wrapper
    return func(*args, **kwargs)
  File "transformers/modeling_utils.py", line 2311, in _from_config
    model = cls(config, **kwargs)
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 611, in __init__
    self.model = DeepseekV3Model(config)
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 533, in __init__
    [DeepseekV3DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 533, in <listcomp>
    [DeepseekV3DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 454, in __init__
    self.self_attn = DeepseekV3Attention(config=config, layer_idx=layer_idx)
  File "transformers/models/deepseek_v3/modeling_deepseek_v3.py", line 343, in __init__
    self.qk_head_dim = config.qk_head_dim
  File "transformers/configuration_utils.py", line 207, in __getattribute__
    return super().__getattribute__(key)
AttributeError: 'DeepseekV3Config' object has no attribute 'qk_head_dim'. Did you mean: 'v_head_dim'?
```

After this change, everything works fine and we can still get the correct dummy model,
(though you are still likely need to manually copy some code files, e.g. `modeling_deepseek.py`)
e.g., via:

```bash
python scripts/init_random_model.py \
--hf_model_path /models/Kimi-K2-Instruct-0905 \
--new_config_path tests/special_e2e/ppo_trainer/expert_parallel/qwen2moe_minimal.json \
--output_path /dummy_models/moonshotai/Kimi-K2-Instruct-0905
--trust_remote_code
```

We get:
```logs
$ du -sh /models/Kimi-K2-Instruct-0905/
959G    /models/Kimi-K2-Instruct-0905/
$ du -sh /dummy_models/moonshotai/Kimi-K2-Instruct-0905
26G     /dummy_models/moonshotai/Kimi-K2-Instruct-0905
$  ls /dummy_models/moonshotai/Kimi-K2-Instruct-0905
chat_template.jinja        model-00001-of-00006.safetensors  model-00005-of-00006.safetensors  tiktoken.model
config.json                model-00002-of-00006.safetensors  model-00006-of-00006.safetensors  tokenization_kimi.py
configuration_deepseek.py  model-00003-of-00006.safetensors  model.safetensors.index.json      tokenizer_config.json
generation_config.json     model-00004-of-00006.safetensors  special_tokens_map.json
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>